### PR TITLE
Converted to lazy load of lock to prevent NPE during constructor

### PR DESCRIPTION
**Pull request by ThisIsUnique**
Updated ExecutionContexThreadedImpl to use lazy loading of the lock variable in the accessor.  This prevents null pointer exceptions during super class constructor execution as in the below stack trace(It no longer happens in the app).  Sub-classes and others can still access lock via the accessor.

```
postBegin:530, ExecutionContextThreadedImpl (org.datanucleus)
transactionStarted:723, ExecutionContextImpl (org.datanucleus)
internalBegin:184, TransactionImpl (org.datanucleus)
begin:157, TransactionImpl (org.datanucleus)
joinTransaction:120, JTAJCATransactionImpl (org.datanucleus)
<init>:64, JTAJCATransactionImpl (org.datanucleus)
initialise:307, ExecutionContextImpl (org.datanucleus)
<init>:257, ExecutionContextImpl (org.datanucleus)
<init>:51, ExecutionContextThreadedImpl (org.datanucleus)
create:65, ExecutionContextPool (org.datanucleus)
checkOut:116, ExecutionContextPool (org.datanucleus)
getExecutionContext:1339, PersistenceNucleusContextImpl (org.datanucleus)
<init>:140, JDOPersistenceManager (org.datanucleus.api.jdo)
newPM:924, JDOPersistenceManagerFactory (org.datanucleus.api.jdo)
getPersistenceManager:906, JDOPersistenceManagerFactory (org.datanucleus.api.jdo)
getPersistenceManager:886, JDOPersistenceManagerFactory (org.datanucleus.api.jdo)
getPersistenceManager:193, ManagedConnectionImpl (org.datanucleus.jdo.connector)
internalBegin:123, ContainerLocalTransaction (org.datanucleus.jdo.connector)
begin:48, ContainerLocalTransaction (org.datanucleus.jdo.connector)
begin:601, AdapterLayer (weblogic.connector.security.layer)
enListResource:97, LocalTxConnectionHandler (weblogic.connector.transaction.outbound)
createConnectionHandle:366, ConnectionHandlerBaseImpl (weblogic.connector.outbound)
createConnectionHandle:401, ConnectionInfo (weblogic.connector.outbound)
getConnection:351, ConnectionManagerImpl (weblogic.connector.outbound)
allocateConnection:135, ConnectionManagerImpl (weblogic.connector.outbound)
getConnection:82, PersistenceManagerFactoryImpl (org.datanucleus.jdo.connector)
getPersistenceManager:111, PersistenceManagerFactoryImpl (org.datanucleus.jdo.connector)
```

### CODE REVIEW

**Review by chrisco484 — COMMENTED** [review]
Is it worth investigating whether a two phase initialization approach would work better? This is adopted by most frameworks where there can be hierarchies of objects with parent/child relationships. It makes things a lot clearer and reduces the chance of the problem you've seen occurring.

e.g.

- Instantiation - via construction - does basic setting of attributes, establishes any relationships with other objects e.g. but does no other initialization stuff - just bare bones construction of the object graph i.e. nothing that requires locks
- Initialization - via an init() method that can do more invasive initialization with a "fully constructed" object and so, for example, lock has already been established and calling any overridden methods of derived classes (if any) work correctly. The objects within the object graph can be initialized in either top down or bottom up approach as appropriate.

**Comment by andyjefferson** [comment]
Or just put 
`protected Lock lock = new ReentrantLock();`
initialising it in the variable decl, rather than the constructor. 
Since I don't get any NPE in superclass constructor, nor see how one can happen, could you try the above first?

**Comment by ThisIsUnique** [comment]
The first change I attempted was in fact to initialize lock with the declaration.  What I found out was that instance variables are initialized before the constructor of the declaring class but not before the constructor of the super class.  So I built this test case:

```
public class SuperClass
{
    public SuperClass()
    {
        method();
        this.method();
    }

    public void method()
    {
        System.out.println("SuperClass");
    }
}
```

```
public class SubClass extends SuperClass
{
    protected String value = new String("Value");

    public SubClass()
    {
        super();
        method();
        this.method();
        super.method();
    }

    public void method()
    {
        System.out.println("Subclass has value: " + value);
    }

    public static void main(String[] args)
    {
        new SubClass();
    }
}
```

Running SubClass produces the following output:
```
Subclass has value: null
Subclass has value: null
Subclass has value: Value
Subclass has value: Value
SuperClass
```

I did consider the separation of construction and initialization but that seemed more like a 6.0 goal.  I thought that first the correction of the issue should be done and then the larger question of "Is there a better way?" could be addressed. 
So that's why I decided to go with the lazy load here.

**Comment by chrisco484** [comment]
My concern with this fix is that if the root cause of the problem was the result of code executed from the context of the constructor(s) of ExecutionContextThreadedImpl's superclass(es) accessing a partially constructed ExecutionContextThreadedImpl instance then that root cause has not been addressed. The change fixes one symptom in one particular scenario.
Accessing a partially constructed ExecutionContextThreadedImpl may be like time bomb ready to go off under a different scenario or with some apparently benign code change made in the future.

**Pull request merged**
