### PR TITLE
Performance optimization

### PR DESCRIPTION
**Pull request by kraendavid**

### CODE REVIEW

**Comment by chrisco484** [comment]
@kraendavid I wasn't sure what the purpose of the temporary 'updated' Set was. I'm sure there's a good reason but I couldn't work it out myself. Maybe due to recursion a recursive call needs to see the original Set? (but then couldn't that be achieved by only adding to the Set after the recursive call?) - don't know but losing sleep not being able to work it out ;)

**Comment by kraendavid** [comment]
Hi @chrisco484 
HashSet is faster lookup than Concurrent versions - that is the reason for using HashSet.
But since this is used on concurrent environment we have to make field volatile and assign a new temporary HashSet when changing the content of the HashSet.
So we want the fast lookup from HashSet - but still work in concurrent environment.
And this is all due to the fact that this set very fast will become stable and fully initialized - and thus only have lookup against it.
So we take the cost of being a little slower until fully initialized - but once initialized it is the fastest at runtime.
Did that explain it?

**Comment by chrisco484** [comment]
> Hi @chrisco484 Did that explain it?

Yes, that explains it, thanks.

We have an massive enterprise app with ~3500 persistent classes so I was worried that the HashSet "copy from collection constructor" will be doing a lot of copying up until the point that initialization of all classes is complete.

**Comment by chrisco484** [comment]
@kraendavid Given that we assume calls to getInitialisedClassForClass() could occur concurrently I was wondering if this call:

`Set<Class<?>> updated = new HashSet<>(initializedPcClasses);`

needs to be rearranged so that the call to the constructor is wrapped within a synchronized block to avoid the chance of the constructor copying items in the Set whilst another thread is modifying Set i.e. adding a new class.

e.g.

```
Set<Class<?>> updated;
synchronized
{
   updated = new HashSet<>(initializedPcClasses);
}

```
 
The synchronized block would only be reached whilst classes are being initialized so this would have no affect on performance after initialization.

**Pull request merged**
