### PR TITLE
Proposal of ability to create metadata for embedded collections/arrays/maps

### PR DESCRIPTION
**Pull request by TikhomirovSergey**
This proposal is related to https://github.com/datanucleus/datanucleus-mongodb/pull/49

It seems such metadata has being ignored for some reason. I would be happy to discuss it and make some improvements if it is necessary.

### CODE REVIEW

**Comment by andyjefferson** [comment]
What does that mean "create metadata for embedded collections/arrays/maps"? People already can specify metadata for such things and have them represented in org.datanucleus.metadata classes, what is "ignored"? Talking just about MongoDB here? What impact has this on RDBMS use-cases? i.e when all tests are run, such as JDO TCK, JPA TCK

**Comment by TikhomirovSergey** [comment]
@andyjefferson 
Hello. Without these changes I have such strings in console output
```
org.datanucleus.store.schema.table.CompleteClassTable processEmbeddedMember
WARNING: Member hello.world.mongo.Product.processingHistoryItems is an embedded array. Not yet supported. Ignoring
org.datanucleus.store.schema.table.CompleteClassTable processEmbeddedMember
WARNING: Member hello.world.mongo.Data.products is an embedded collection. Not yet supported. Ignoring
org.datanucleus.store.schema.table.CompleteClassTable processEmbeddedMember
WARNING: Member hello.world.mongo.Data.promises is an embedded collection. Not yet supported. Ignoring
```
You can find it in `org.datanucleus.store.schema.table.CompleteClassTable`
MongoDB uses this functionality.

My gradle configuration:
```gradle
    compile (group: 'org.datanucleus', name: 'datanucleus-accessplatform-jdo-mongodb', version: '5.1.11') {
        exclude group: 'org.mongodb', module: 'mongodb-driver'
    }
    datanucleus group: 'org.datanucleus', name: 'datanucleus-jdo-query', version: '5.0.5'
    compile group: 'org.mongodb', name: 'mongodb-driver', version: '3.8.0'
    compile group: 'javax.annotation', name: 'javax.annotation-api', version: '1.3.2'
```
image

Yes. I can do something wrong. So it is cool to fing some great solution without merging of these changes.

**Comment by andyjefferson** [comment]
I've no interest in how you BUILD your testcase (i.e Gradle), and I don't use Gradle anyway so no idea what that is showing. I've interest in WHAT you are trying to model here. Based on what you posted over on that other PR you have a field that is an embedded collection (see http://www.datanucleus.org:15080/products/accessplatform_5_2/jdo/mapping.html#embedded_collection ). If that is the situation, then why does your PR here still include code that says 
"Member " + mmd.getFullFieldName() + " is an embedded collection. Not yet supported. Ignoring"
Either CompleteClassTable (with your PR) now supports this field type or it doesn't. Which ?

CompleteClassTable defines a schema, not metadata; hence why I was querying your original description of this PR. Your PR changes the structure of the embedded handling, and I don't understand what it is trying to do, so need clarification.

If you are going to add support for embedded collections (and maps, arrays) then you need to say HOW this will be represented in the CompleteClassTable. I referred you to issue tracker https://github.com/datanucleus/datanucleus-core/issues/30 which is to cover supporting these field types. But it doesn't define how they will be supported yet. What will be stored in "mappingByEmbeddedMember" ? What will be stored in "mappingByMember", and in "columnByName"?

HOW will an embedded collection be supported with MongoDB? You have to DEFINE what the data will look like before implementing it. In RDBMS it is stored in a separate (join) table. In MongoDB it presumably will have to be NESTED into the owner object (so the nested flag doesn't apply for those fields then?).

**Comment by TikhomirovSergey** [comment]
@andyjefferson I will provide more information ASAP

**Comment by andyjefferson** [comment]
Seemingly what you are doing here is "support having a nested embedded collection" (not supported on ANY datastore, not even RDBMS), whereas we only support "nested embedded PC". Sadly your PR here deletes an amount of code from `CompleteClassTable` (that recurses through the method `processEmbeddedMember`) meaning that column namings for nested embedded PC will now no longer work if the user has overridden them in metadata. Consequently I'm closing this as won't accept, since it breaks current code.

That shouldn't deter you from trying to support this. I've added some changes to CompleteClassTable to do some things for nested embedded collection/array, but there are various TODOs left. Maps are not touched yet either. But the problem there is deciding how to store Map key/value column information in `CompleteClassTable`, which goes back to issue #30

**Pull request closed without merging**
