### PR TITLE
NUCCORE-1381: Fix property validation being triggered twice on enti…

### PR DESCRIPTION
**Pull request by RodrigoQuesadaDev**
Hi, this is the PR for the ticket NUCCORE-1381 I just opened today. Thanks!

### CODE REVIEW

**Comment by andyjefferson** [comment]
Lifecycle events are called to meet the part of the JDO/JPA specs about lifecycle events so that people can have lifecycle listeners and intercept such events. Simply DELETING an event is not an option, and fails the JPA TCK. That is not the way to fix whatever issue you have.

**Comment by RodrigoQuesadaDev** [comment]
Hello Andy, thanks for checking this PR and pointing me out that is not okay; interesting enough though, it passes the JDO tests (general tests at least) and the tests I have for my code (where I sure use a lot of callbacks in order to fulfill some interesting requirements). I apologize for submitting this wrong PR, next time I submit a PR (if I get the time to setup TCKs) it won't break anything, I can assure you that.

The issue I was trying to address is not something that is really affecting me (but maybe someone else?), it is simply that bean validation for properties using JDO (http://www.datanucleus.org/products/datanucleus/jdo/bean_validation.html) is triggered twice during entity creation, and that's simply not optimal (not that it really affects me as I said). I have tests that prove what I'm stating here so if you were to be interested on this matter I can zip them to you (well, I would have to modify them slightly before sending them because they are written using JBehave).

Cheers,
Rodrigo

**Comment by andyjefferson** [comment]
Hi Rodrigo,
suggest you look further along the stack trace ... the method that this calls. JDOCallbackHandler.prePersist. That is what calls the validator ... and also for preStore. Maybe only needs one or the other of those?

**Comment by RodrigoQuesadaDev** [comment]
Yeah, I had already looked into that, I just wasn't careful enough to run all tests and check if the line I removed was really unnecessary (I'm only using JDO at the moment and don't plan on using JPA). I have some code that uses preStore and postCreate callbacks, and I had to add a check in order to prevent the code on preStore from running on entity creation; so the solution to this issue is probably similar (although I guess I probably have to be careful not to break the validation properties functionality http://www.datanucleus.org/products/accessplatform/persistence_properties.html#validation). In any case thanks for the suggestion Andy, I'll probably work on fixing issue later. :)

**Pull request closed without merging**
